"""Regroup the canonical 1,000-phase roadmap into 10 stages x 100 phases.

Source of phase content: docs/MASTER_ROADMAP_1000_PHASES.json as generated by
scripts/generate_master_roadmap_1000.py (20 x 50 definitions).

This script preserves every phase's number, title, category, objective,
tasks, files, dependencies, tests, and acceptance criteria exactly, and only
remaps stage_number/stage_name into the approved 10-stage organization:

  STAGE 01 (0001-0100) Repository Audit, Architecture and Service Reliability
  STAGE 02 (0101-0200) Premium Windows Application and Conversational Intelligence
  STAGE 03 (0201-0300) Persistent Memory, Planning and Task Decomposition
  STAGE 04 (0301-0400) Multi-Agent Orchestration and Adaptive Integration
  STAGE 05 (0401-0500) Browser Automation and Windows Desktop Execution
  STAGE 06 (0501-0600) Software Engineering, Git and Code Review
  STAGE 07 (0601-0700) Workflow Automation, Security and Trust
  STAGE 08 (0701-0800) Verification, Recovery, Performance and Cost
  STAGE 09 (0801-0900) Personalization, Observability and Quality
  STAGE 10 (0901-1000) Production Hardening and Long-Term Evolution

Validation: exactly 1,000 phases, contiguous 0001-1000, unique ids/titles,
10 stages x 100 phases each.
"""
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
JSON_PATH = DOCS_DIR / "MASTER_ROADMAP_1000_PHASES.json"
MD_PATH = DOCS_DIR / "MASTER_ROADMAP_1000_PHASES.md"

NEW_STAGES = [
    (1, "Repository Audit, Architecture and Service Reliability", 1, 100),
    (2, "Premium Windows Application and Conversational Intelligence", 101, 200),
    (3, "Persistent Memory, Planning and Task Decomposition", 201, 300),
    (4, "Multi-Agent Orchestration and Adaptive Integration", 301, 400),
    (5, "Browser Automation and Windows Desktop Execution", 401, 500),
    (6, "Software Engineering, Git and Code Review", 501, 600),
    (7, "Workflow Automation, Security and Trust", 601, 700),
    (8, "Verification, Recovery, Performance and Cost", 701, 800),
    (9, "Personalization, Observability and Quality", 801, 900),
    (10, "Production Hardening and Long-Term Evolution", 901, 1000),
]


def stage_for_phase(n):
    for (sno, sname, start, end) in NEW_STAGES:
        if start <= n <= end:
            return sno, sname
    raise ValueError(f"phase out of range: {n}")


def main():
    payload = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    phases = payload["phases"]
    assert len(phases) == 1000, f"expected 1000 phases, got {len(phases)}"

    for p in phases:
        sno, sname = stage_for_phase(p["phase_number"])
        p["stage_number"] = sno
        p["stage_name"] = sname

    ids = [p["phase_id"] for p in phases]
    assert ids == [f"PHASE {i:04d}" for i in range(1, 1001)], "numbering broken"
    assert len(set(ids)) == 1000
    assert len({p["title"] for p in phases}) == 1000
    for (sno, sname, start, end) in NEW_STAGES:
        got = [p for p in phases if p["stage_number"] == sno]
        assert len(got) == 100, f"stage {sno} has {len(got)} phases"
        assert min(x["phase_number"] for x in got) == start
        assert max(x["phase_number"] for x in got) == end

    payload["stages"] = 10
    payload["stage_layout"] = [
        {"stage_number": sno, "stage_name": sname, "start": start, "end": end}
        for (sno, sname, start, end) in NEW_STAGES
    ]
    payload["generated_note"] = (
        "10 stages x 100 phases. Phase content generated from "
        "scripts/generate_master_roadmap_1000.py area definitions; stage "
        "grouping applied by scripts/regroup_roadmap_10x100.py. Each phase "
        "remains independently verifiable."
    )
    JSON_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    lines = []
    lines.append("# WinAI-OE — Master Roadmap (Exactly 1,000 Development Phases)")
    lines.append("")
    lines.append("Product: Secure, adaptive, autonomous Windows AI environment (WinAI-OE).")
    lines.append("Organization: 10 stages x 100 phases. Each phase is independently verifiable.")
    lines.append("")
    lines.append("## Stage Index")
    lines.append("")
    for (sno, sname, start, end) in NEW_STAGES:
        lines.append(f"- STAGE {sno:02d} — {sname} (PHASE {start:04d}–{end:04d})")
    lines.append("")
    for (sno, sname, start, end) in NEW_STAGES:
        lines.append(f"## STAGE {sno:02d} — {sname}")
        lines.append("")
        lines.append(f"Phases {start:04d}–{end:04d}")
        lines.append("")
    for p in phases:
        lines.append(f"### {p['phase_id']}")
        lines.append(f"Title: {p['title']}")
        lines.append(f"Category: {p['category']}")
        lines.append(f"Objective: {p['objective']}")
        lines.append(f"Current State: {p['current_state']}")
        lines.append("Implementation Tasks:")
        for t in p["implementation_tasks"]:
            lines.append(f"- {t}")
        lines.append(f"Files or Components: {p['files_or_components']}")
        lines.append(f"Dependencies: {p['dependencies']}")
        lines.append(f"Security Considerations: {p['security_considerations']}")
        lines.append(f"Automated Tests: {p['automated_tests']}")
        lines.append(f"Manual Verification: {p['manual_verification']}")
        lines.append(f"Acceptance Criteria: {p['acceptance_criteria']}")
        lines.append(f"Completion Evidence: {p['completion_evidence']}")
        lines.append(f"Rollback Strategy: {p['rollback_strategy']}")
        lines.append("")
    MD_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Regrouped {len(phases)} phases into 10 stages x 100.")


if __name__ == "__main__":
    main()
